import type { CourseSnapshot, SectionId } from './types.js';
import type { ParsedSnapshot } from './parse_existing.js';
import {
  renderIdentifiers, renderAssignmentGroups, renderModules,
  renderUpdateLog, wrapSection,
  type UpdateLogRow,
} from './render_sections.js';

interface ComposeInput {
  snapshot: CourseSnapshot;
  hostBase: string;
  existing?: ParsedSnapshot;
  /** Row to prepend to the Update Log. Omit on first run to skip the row. */
  newLogRow?: UpdateLogRow;
}

/** Render the markdown body for a given managed-section id from current
 *  snapshot state. */
function renderSection(id: SectionId, snap: CourseSnapshot, hostBase: string, existing?: ParsedSnapshot, newLogRow?: UpdateLogRow): string {
  switch (id) {
    case 'identifiers':
      return renderIdentifiers(snap, hostBase);
    case 'assignment-groups':
      return renderAssignmentGroups(snap);
    case 'modules':
      return renderModules(snap);
    case 'update-log': {
      const existingRows = existing?.existingUpdateLogRows ?? [];
      const allRows: UpdateLogRow[] = [];
      if (newLogRow) allRows.push(newLogRow);
      // Existing rows are already raw markdown strings; we need to splice them back as-is.
      // Re-render with newest-first ordering by treating existing rows as raw markdown lines.
      const header = '| Date | Semester | What changed | By |\n|---|---|---|---|';
      const newPrependLine = newLogRow ?
        `| ${newLogRow.date} | ${newLogRow.semester} | ${newLogRow.what} | ${newLogRow.by} |` : null;
      const lines = [header];
      if (newPrependLine) lines.push(newPrependLine);
      for (const row of existingRows) lines.push(row);
      // Suppress unused-var warning for allRows by using it
      void allRows;
      return lines.join('\n');
    }
  }
}

const DEFAULT_PROSE = {
  beforeUpdateLog: () => '',
  afterUpdateLog: '\n\n---\n\n## Course identifiers\n\n',
  afterIdentifiers: '\n\n---\n\n## Assignment groups\n\nGroups + counts as of last snapshot.\n\n',
  afterAssignmentGroups: '\n\n---\n\n## Modules\n\n',
  afterModules: '\n\n---\n\n_End of auto-managed sections. Add hand-written reference content below — it will be preserved across re-runs of `snapshot_course`._\n',
};

/** Compose the full snapshot markdown.
 *
 *  On first run (no `existing`): emits the canonical structure with prose
 *  scaffolding between auto-managed sections.
 *
 *  On re-run (`existing` provided): walks the existing document's segment
 *  order — verbatim prose preserved, managed section bodies regenerated.
 *  Any of the four required sections that are MISSING from the existing
 *  document get appended at the bottom (e.g. if the user deleted one). */
export function composeSnapshot(input: ComposeInput): string {
  const { snapshot, hostBase, existing, newLogRow } = input;

  if (!existing) {
    return composeFirstRun(snapshot, hostBase, newLogRow);
  }

  const REQUIRED: SectionId[] = ['update-log', 'identifiers', 'assignment-groups', 'modules'];
  const seen = new Set<SectionId>();
  const parts: string[] = [];

  for (const seg of existing.orderedSegments) {
    if ('prose' in seg) {
      parts.push(seg.prose);
    } else {
      const body = renderSection(seg.sectionId, snapshot, hostBase, existing, newLogRow);
      parts.push(wrapSection(seg.sectionId, body));
      seen.add(seg.sectionId);
    }
  }

  // Append any required sections the existing doc was missing
  for (const id of REQUIRED) {
    if (!seen.has(id)) {
      const body = renderSection(id, snapshot, hostBase, existing, newLogRow);
      parts.push(`\n\n<!-- Section "${id}" was missing; appended on re-run. -->\n${wrapSection(id, body)}\n`);
    }
  }

  return parts.join('');
}

function composeFirstRun(snap: CourseSnapshot, hostBase: string, newLogRow?: UpdateLogRow): string {
  const title = `# ${snap.course.title} — Course Reference & Refresh Playbook`;
  const intro =
`> Auto-generated by \`snapshot_course\`. Each section delimited by an
> \`AUTO:start\` / \`AUTO:end\` HTML comment pair is regenerated on every
> re-run. Hand-written prose outside those markers is preserved verbatim.

`;

  // First-run Update Log: one row (the new log row if provided, otherwise empty).
  const firstLogRow: UpdateLogRow | undefined =
    newLogRow ?? { date: '(now)', semester: '—', what: 'Initial snapshot', by: 'snapshot_course' };
  const updateLogBody = renderUpdateLog([firstLogRow]);

  return [
    title,
    '',
    intro,
    '## Update Log',
    '',
    wrapSection('update-log', updateLogBody),
    DEFAULT_PROSE.afterUpdateLog.trim(),
    '',
    wrapSection('identifiers', renderIdentifiers(snap, hostBase)),
    DEFAULT_PROSE.afterIdentifiers.trim(),
    '',
    wrapSection('assignment-groups', renderAssignmentGroups(snap)),
    DEFAULT_PROSE.afterAssignmentGroups.trim(),
    '',
    wrapSection('modules', renderModules(snap)),
    DEFAULT_PROSE.afterModules,
  ].join('\n');
}
