import { loadCatalog, type CapabilityCatalog, type CatalogPattern, type SupportStatus } from '@canvas-toolchain/canvas-design-studio/dist/tools/showcase/catalog.js';

export interface ShowCanvasCapabilitiesInput {
  category?: string;
  supportStatus?: SupportStatus;
}

export interface ShowCanvasCapabilitiesResult {
  catalogVersion: number;
  updated: string;
  catalog: string;
  patternIds: string[];
}

export async function showCanvasCapabilities(
  input: ShowCanvasCapabilitiesInput,
): Promise<ShowCanvasCapabilitiesResult> {
  const catalog = loadCatalog();
  const filtered = applyFilters(catalog.patterns, input);
  const markdown = formatMarkdown(catalog, filtered, input);
  return {
    catalogVersion: catalog.version,
    updated: catalog.updated,
    catalog: markdown,
    patternIds: filtered.map((p) => p.id),
  };
}

function applyFilters(
  patterns: CatalogPattern[],
  input: ShowCanvasCapabilitiesInput,
): CatalogPattern[] {
  return patterns.filter((p) => {
    if (input.category && p.category !== input.category) return false;
    if (input.supportStatus && p.supportStatus !== input.supportStatus) return false;
    return true;
  });
}

function isSupportedTier(p: CatalogPattern): boolean {
  return p.supportStatus === 'supported' || p.supportStatus === 'partial';
}

function formatMarkdown(
  catalog: CapabilityCatalog,
  patterns: CatalogPattern[],
  input: ShowCanvasCapabilitiesInput,
): string {
  const lines: string[] = [];
  lines.push('# Canvas Capabilities');
  lines.push('');
  lines.push(`Updated ${catalog.updated} (catalog v${catalog.version})`);
  lines.push('');
  lines.push('---');
  lines.push('');

  const supported = patterns.filter(isSupportedTier);
  const aspirational = patterns.filter((p) => p.supportStatus === 'aspirational');

  if (supported.length > 0 && input.supportStatus !== 'aspirational') {
    lines.push('## ✅ Currently Supported');
    lines.push('');
    appendCategoryGrouped(lines, catalog, supported);
  }

  if (aspirational.length > 0 && input.supportStatus !== 'supported' && input.supportStatus !== 'partial') {
    lines.push('## 🛠 Aspirational (not yet generated by CDS)');
    lines.push('');
    lines.push('These patterns are Canvas-safe but CDS does not currently produce them.');
    lines.push('Listed for awareness and as a roadmap signal.');
    lines.push('');
    appendCategoryGrouped(lines, catalog, aspirational);
  }

  return lines.join('\n').replace(/\n{3,}/g, '\n\n');
}

function appendCategoryGrouped(
  lines: string[],
  catalog: CapabilityCatalog,
  patterns: CatalogPattern[],
): void {
  for (const cat of catalog.categories) {
    const catPatterns = patterns.filter((p) => p.category === cat.id);
    if (catPatterns.length === 0) continue;
    lines.push(`### ${cat.name}`);
    lines.push('');
    for (const p of catPatterns) {
      const partialMark = p.supportStatus === 'partial' ? ' *(partial)*' : '';
      lines.push(`#### ${p.name}  (\`${p.id}\`)${partialMark}`);
      lines.push('');
      lines.push(p.description.trim());
      lines.push('');
      lines.push(`**When to use:** ${p.whenToUse.trim()}`);
      lines.push('');
      lines.push(`To see this pattern rendered, ask for \`preview_canvas_pattern\` with \`patternId: "${p.id}"\`.`);
      lines.push('');
    }
  }
}
