import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { existsSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { homedir, tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  managedCanvasBackupConfigPath,
  renderCanvasBackupConfig,
  writeManagedCanvasBackupConfig,
} from '../../src/passthrough/canvas_backup_config.js';

let tmpHome: string;

beforeEach(() => {
  tmpHome = mkdtempSync(join(tmpdir(), 'cc-canvas-backup-cfg-'));
  process.env.CC_HOME = tmpHome;
});

afterEach(() => {
  delete process.env.CC_HOME;
  rmSync(tmpHome, { recursive: true, force: true });
});

const SECRET_TOKEN = 'super-secret-canvas-token-xyz';

function seedCanvasConfig(host = 'example.instructure.com', token = SECRET_TOKEN): void {
  writeFileSync(
    join(tmpHome, 'canvas-config.json'),
    JSON.stringify({
      host,
      token,
      configuredAt: '2026-08-01T00:00:00.000Z',
      lastValidatedAt: '2026-08-01T00:00:00.000Z',
    }),
    'utf-8',
  );
}

describe('renderCanvasBackupConfig', () => {
  it('includes base_url and the four required archive keys', () => {
    const toml = renderCanvasBackupConfig('https://example.instructure.com', {
      semester: 'Fall',
      year: '2026',
      root: '/tmp/archives',
      downloadWorkers: 4,
    });

    expect(toml).toContain('base_url = "https://example.instructure.com"');
    expect(toml).toMatch(/\[canvas\]/);
    expect(toml).toMatch(/\[archive\]/);
    expect(toml).toContain('root = "/tmp/archives"');
    expect(toml).toContain('year = "2026"');
    expect(toml).toContain('semester = "Fall"');
    expect(toml).toContain('token_env = "CANVAS_TOKEN"');
    expect(toml).toContain('download_workers = 4');
    expect(toml).toMatch(/Generated by Command and Control/);
  });

  it('never embeds a token value (only token_env)', () => {
    const toml = renderCanvasBackupConfig('https://example.instructure.com', {
      semester: 'Spring',
    });
    expect(toml).not.toMatch(/^\s*token\s*=/m);
    expect(toml).toContain('token_env = "CANVAS_TOKEN"');
  });

  it('throws on missing or empty semester', () => {
    expect(() =>
      renderCanvasBackupConfig('https://example.instructure.com', {
        semester: '',
      }),
    ).toThrow(/SEMESTER_REQUIRED|semester/i);

    expect(() =>
      renderCanvasBackupConfig('https://example.instructure.com', {
        semester: '   ',
      }),
    ).toThrow(/SEMESTER_REQUIRED|semester/i);

    expect(() =>
      // @ts-expect-error — intentional missing field
      renderCanvasBackupConfig('https://example.instructure.com', {}),
    ).toThrow(/SEMESTER_REQUIRED|semester/i);
  });

  it('escapes Windows-style backslash paths without mangling them', () => {
    const winRoot = 'D:\\Courses\\CanvasArchive';
    const toml = renderCanvasBackupConfig('https://example.instructure.com', {
      semester: 'Fall',
      root: winRoot,
    });
    // TOML basic string: backslashes doubled
    expect(toml).toContain('root = "D:\\\\Courses\\\\CanvasArchive"');
    // Round-trip: unescaping recovers the original path
    const match = toml.match(/root = "([^"]*)"/);
    expect(match).not.toBeNull();
    const unescaped = match![1].replace(/\\"/g, '"').replace(/\\\\/g, '\\');
    expect(unescaped).toBe(winRoot);
  });

  it('applies defaults for root, year, and downloadWorkers', () => {
    const toml = renderCanvasBackupConfig('https://example.instructure.com', {
      semester: 'Summer',
    });
    const expectedRoot = join(homedir(), 'CanvasArchive');
    const escapedRoot = expectedRoot.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    expect(toml).toContain(`root = "${escapedRoot}"`);
    expect(toml).toContain(`year = "${new Date().getFullYear()}"`);
    expect(toml).toContain('download_workers = 6');
  });
});

describe('writeManagedCanvasBackupConfig', () => {
  it('writes TOML with base_url from the stored bare host and the four required keys', () => {
    seedCanvasConfig('school.instructure.com');

    const { path, baseUrl } = writeManagedCanvasBackupConfig({
      semester: 'Fall',
      year: '2026',
      root: join(tmpHome, 'archives'),
    });

    expect(baseUrl).toBe('https://school.instructure.com');
    expect(path).toBe(managedCanvasBackupConfigPath());
    expect(path).toBe(join(tmpHome, 'canvas-backup.generated.toml'));
    expect(existsSync(path)).toBe(true);

    const toml = readFileSync(path, 'utf-8');
    expect(toml).toContain('base_url = "https://school.instructure.com"');
    expect(toml).toContain('year = "2026"');
    expect(toml).toContain('semester = "Fall"');
    expect(toml).toContain('token_env = "CANVAS_TOKEN"');
    expect(toml).toMatch(/root = "/);
  });

  it('NEVER writes the Canvas API token value into the generated file', () => {
    seedCanvasConfig('example.instructure.com', SECRET_TOKEN);

    const { path } = writeManagedCanvasBackupConfig({ semester: 'Fall' });
    const toml = readFileSync(path, 'utf-8');

    expect(toml).not.toContain(SECRET_TOKEN);
    expect(toml).not.toMatch(/^\s*token\s*=/m);
    expect(toml).toContain('token_env = "CANVAS_TOKEN"');
  });

  it.skipIf(process.platform === 'win32')('writes the config file with 0o600 permissions', () => {
    seedCanvasConfig();

    const { path } = writeManagedCanvasBackupConfig({ semester: 'Spring' });
    const stats = statSync(path);
    expect(stats.mode & 0o777).toBe(0o600);
  });

  it('throws when semester is missing/empty', () => {
    seedCanvasConfig();
    expect(() => writeManagedCanvasBackupConfig({ semester: '' })).toThrow(/SEMESTER_REQUIRED|semester/i);
  });

  it('throws when Canvas is not configured', () => {
    expect(() => writeManagedCanvasBackupConfig({ semester: 'Fall' })).toThrow(/CANVAS_NOT_CONFIGURED/);
  });
});
