import { existsSync, mkdirSync, renameSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { canvasBaseUrl } from '@canvas-toolchain/shared-types';
import { getCcHomePath } from '../kb/config.js';
import { loadCanvasConfig } from '../tools/setup_canvas.js';

export interface CanvasBackupPrefs {
  root?: string;
  year?: string;
  semester: string;
  downloadWorkers?: number;
}

/** Path of the C&C-managed Canvas Backup config (under ~/.command-and-control). */
export function managedCanvasBackupConfigPath(): string {
  return join(getCcHomePath(), 'canvas-backup.generated.toml');
}

/** Escape a string for use inside a TOML basic string ("..."). */
function escapeTomlString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

/**
 * Render a Canvas Backup TOML config.
 *
 * SECURITY: never embeds the API token. Emits token_env = "CANVAS_TOKEN" so the
 * caller can pass the token only in the child-process environment.
 */
export function renderCanvasBackupConfig(baseUrl: string, prefs: CanvasBackupPrefs): string {
  const semester = prefs.semester?.trim();
  if (!semester) {
    throw new Error(
      'SEMESTER_REQUIRED: semester must be provided (e.g. "Fall", "Spring", "Summer"). ' +
        'It is never guessed because a wrong semester silently misfiles the archive.',
    );
  }

  const root = prefs.root ?? join(homedir(), 'CanvasArchive');
  const year = prefs.year ?? String(new Date().getFullYear());
  // Coerce defensively: a non-integer would render as invalid TOML (or NaN),
  // which Canvas Backup only reports as an opaque preflight failure.
  const requested = prefs.downloadWorkers ?? 6;
  if (!Number.isInteger(requested) || requested < 1 || requested > 32) {
    throw new Error(
      `DOWNLOAD_WORKERS_INVALID: downloadWorkers must be a whole number from 1 to 32 (got ${String(requested)}).`,
    );
  }
  const downloadWorkers = requested;

  return [
    '# Generated by Command and Control — do not hand-edit; will be overwritten by setup_canvas_backup.',
    '',
    '[canvas]',
    `base_url = "${escapeTomlString(baseUrl)}"`,
    'token_env = "CANVAS_TOKEN"',
    '',
    '[archive]',
    `root = "${escapeTomlString(root)}"`,
    `year = "${escapeTomlString(year)}"`,
    `semester = "${escapeTomlString(semester)}"`,
    `download_workers = ${downloadWorkers}`,
    '',
  ].join('\n');
}

/**
 * Write the managed Canvas Backup config from the Canvas connection already
 * configured in Command and Control. Token is never written to disk.
 */
export function writeManagedCanvasBackupConfig(
  prefs: CanvasBackupPrefs,
): { path: string; baseUrl: string } {
  const canvas = loadCanvasConfig();
  const baseUrl = canvasBaseUrl(canvas.host);
  const toml = renderCanvasBackupConfig(baseUrl, prefs);

  const home = getCcHomePath();
  mkdirSync(home, { recursive: true });
  const path = managedCanvasBackupConfigPath();
  const tmpPath = `${path}.tmp`;
  writeFileSync(tmpPath, toml, { encoding: 'utf-8', mode: 0o600 });
  renameSync(tmpPath, path);

  return { path, baseUrl };
}

/** True when the managed config file is present on disk. */
export function managedCanvasBackupConfigExists(): boolean {
  return existsSync(managedCanvasBackupConfigPath());
}
